version: "3.8"

services:
  hytale-server:
    build: .
    image: hytale-server:latest
    container_name: hytale-server
    #restart: unless-stopped
    volumes:
      - ./data/files:/opt/hytale/server
      - ./data/auth:/opt/hytale/tokens
    environment:
      # Set to 1 to run the device code flow inside the container (you still must visit the verification URL)
      - HYTALE_AUTOMATE_DEVICE_FLOW=1
    ports:
      - "5520:5520/udp"
    tty: true
    stdin_open: true
